- name: Create network.
  community.docker.docker_network:
    name: photoprism

- name: Create volumes.
  community.docker.docker_volume:
    name: "{{ volume }}"
  loop:
    - photoprism_app
    - photoprism_db
  loop_control:
    loop_var: volume

- name: Create DB container.
  community.docker.docker_container:
    name: photoprism_db
    image: "mariadb:11.4.2"
    pull: true
    restart_policy: unless-stopped
    security_opts:
      - "seccomp:unconfined"
      - "apparmor:unconfined"
    networks:
      - name: photoprism
    purge_networks: true
    volumes:
      - "photoprism_db:/var/lib/mysql:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    env:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "{{ photoprism_db_password }}"
      MARIADB_ROOT_PASSWORD: "{{ photoprism_db_root_password }}"
    command: "mysqld --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "photoprism",
          "-p{{ photoprism_db_password }}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

- name: Create APP container.
  community.docker.docker_container:
    name: photoprism_app
    image: "photoprism/photoprism:221118-arm64"
    pull: true
    restart_policy: unless-stopped
    security_opts:
      - "seccomp:unconfined"
      - "apparmor:unconfined"
    networks:
      - name: photoprism
    volumes:
      - "photoprism_app:/photoprism/storage:rw"
      - "/media/photos:/photoprism/originals:rw"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
    ports:
      - "{{ tailscale_ip }}:2342:2342"
    env:
      PHOTOPRISM_ADMIN_USER: "{{ photoprism_admin_user }}"
      PHOTOPRISM_ADMIN_PASSWORD: "{{ photoprism_admin_password }}"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "http://{{ tailscale_ip }}:2342/"
      PHOTOPRISM_ORIGINALS_LIMIT: "5000"
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_WORKERS: "3"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: "100"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprism_db:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "{{ photoprism_db_password }}"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_INIT: "update clean tensorflow"
      PHOTOPRISM_FFMPEG_ENCODER: "raspberry"
      PHOTOPRISM_FFMPEG_BITRATE: "32"
      PHOTOPRISM_UID: "1000"
      PHOTOPRISM_GID: "1000"
      PHOTOPRISM_UMASK: "0000"
    devices:
      - "/dev/video11:/dev/video11"
    working_dir: "/photoprism"
